version: '3'

services:
  load_balancer:
    image: nginx:stable
    container_name: load_balancer
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./docker/load-balance/nginx.conf:/etc/nginx/nginx.conf
    links:
      - ap1
      - ap2
    depends_on:
      - ap1
      - ap2

  ap1:
    image: nginx:stable
    container_name: ap1
    restart: always
    ports:
      - "80"
    volumes:
      - ./docker/php-fpm/nginx.conf:/etc/nginx/nginx.conf
      - ./:/var/www/html
    links:
      - php-fpm
    depends_on:
      - php-fpm
    
  ap2:
    image: nginx:stable
    container_name: ap2
    restart: always
    ports:
      - "80"
    volumes:
      - ./docker/php-fpm/nginx.conf:/etc/nginx/nginx.conf
      - ./:/var/www/html
    links:
      - php-fpm
    depends_on:
      - php-fpm

  php-fpm:
    image: bitnami/php-fpm:8.2.11-debian-11-r3
    container_name: php-fpm
    restart: always
    ports:
      - "9000"
    volumes:
      - ./:/var/www/html
    links:
      - mariadb
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:lts
    container_name: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: password
