version: '3'

services:
  nginx:
    image: nginx:stable
    container_name: nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./:/var/www/html
    links:
      - php-fpm
    depends_on:
      - php-fpm

  php-fpm:
    image: bitnami/php-fpm:8.2.11-debian-11-r3
    container_name: php-fpm
    restart: always
    ports:
      - 9000:9000
    volumes:
      - ./:/var/www/html
    links:
      - mariadb
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:lts
    container_name: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: password
